import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

const Color ebonyclay = Color(0xff2b2c3e);
const Color woodsmoke = Color(0xff131317);
const Color botticelli = Color(0xffd7ddea);
const Color balihai = Color(0xff949ebb);
const Color opium = Color(0xff8e6b73);
const Color likeblue = Color.fromARGB(255, 32, 156, 228);

final spotifyIcon = SvgPicture.asset(
  'assets/ico/spotify.svg',
  color: botticelli,
  fit: BoxFit.fill,
);
final chatIcon = SvgPicture.asset(
  'assets/ico/chat.svg',
  color: woodsmoke,
  // height: 30,
  // width: 30,
  fit: BoxFit.fill,
);
final qrIcon = SvgPicture.asset(
  'assets/ico/pan_qr.svg',
  color: Colors.transparent,
  colorBlendMode: BlendMode.color,
  // height: 30,
  // width: 30,
  fit: BoxFit.contain,
);

final doctor = Image.asset(
  'assets/img/dr2.jpg',
  fit: BoxFit.cover,
);
final onb1Img = Image.asset(
  'assets/img/onb1.jpg',
  fit: BoxFit.cover,
  cacheHeight: 1059,
  cacheWidth: 706,
);
final onb2Img = Image.asset(
  'assets/img/onb2.jpg',
  fit: BoxFit.cover,
  cacheHeight: 641,
  cacheWidth: 962,
);
final onb3Img = Image.asset(
  'assets/img/onb3.jpg',
  fit: BoxFit.cover,
  cacheHeight: 1369,
  cacheWidth: 1027,
);

final List<String> tagList = [
  'Hip Hop',
  'Rock',
  'NEFFEX',
  'Arctic Monkeys',
  'Rap',
  'Johnny Cash',
  'Eminem',
  'Drake',
];

PageRouteBuilder defaultPageAnim(
        {required page, Alignment alignment = Alignment.center}) =>
    PageRouteBuilder(
      pageBuilder: (context, animation, animationTime) {
        return page;
      },
      transitionDuration: const Duration(milliseconds: 50),
      reverseTransitionDuration: const Duration(milliseconds: 100),
      transitionsBuilder: (context, animation, animationTime, child) {
        animation = CurvedAnimation(parent: animation, curve: Curves.ease);
        return ScaleTransition(
            scale: animation, alignment: alignment, child: child);
      },
    );

List<String> profanityFilter = [
  'ahole',
  'amcik',
  'andskota',
  'anus',
  'arschloch',
  'arse',
  'ash0le',
  'asholes',
  'ass',
  'assface',
  'assh0le',
  'assh0lez',
  'asshole',
  'assholz',
  'assmonkey',
  'assrammer',
  'asswipe',
  'ayir',
  'azzhole',
  'b00bs',
  'b17ch',
  'b1tch',
  'bassterds',
  'bastard',
  'bastardz',
  'basterds',
  'basterdz',
  'bch',
  'bi7ch',
  'biatch',
  'bich',
  'bitch',
  'blowjob',
  'boffing',
  'boiolas',
  'bollock',
  'boobs',
  'breasts',
  'btch',
  'buceta',
  'bullshit',
  'butthole',
  'buttpirate',
  'buttwipe',
  'c0ck',
  'c0k',
  'cabron',
  'carpetmuncher',
  'cawk',
  'cazzo',
  'chink',
  'chraa',
  'chuj',
  'cipa',
  'clit',
  'cnts',
  'cntz',
  'cock',
  'cockhead',
  'cocksucker',
  'crap',
  'cum',
  'cunt',
  'cuntz',
  'd4mn',
  'damn',
  'daygo',
  'dego',
  'dick',
  'dike',
  'dild0',
  'dild0s',
  'dildo',
  'dilld0',
  'dilld0s',
  'dirsa',
  'dominatricks',
  'dominatrics',
  'dominatrix',
  'dupa',
  'dyke',
  'dziwka',
  'ejackulate',
  'ejakulate',
  'ekto',
  'enculer',
  'enema',
  'faen',
  'fag',
  'fag1t',
  'faget',
  'fagg1t',
  'faggit',
  'faggot',
  'fagit',
  'fagz',
  'faig',
  'fanculo',
  'fanny',
  'fart',
  'fatass',
  'fcuk',
  'feces',
  'feg',
  'felcher',
  'ficken',
  'fitt',
  'flikker',
  'flipping',
  'foreskin',
  'fotze',
  'fuchah',
  'fuck',
  'fucka',
  'fucker',
  'fuckin',
  'fucking',
  'fudgepacker',
  'fukah',
  'fuken',
  'fuker',
  'fukin',
  'fukka',
  'fukkah',
  'fukken',
  'fukker',
  'fukkin',
  'futkretzn',
  'fux0r',
  'g00k',
  'gay',
  'gaybor',
  'gayboy',
  'gaygirl',
  'gayz',
  'goddamned',
  'gook',
  'guiena',
  'h00r',
  'h0ar',
  'h0r',
  'h0re',
  'h4x0r',
  'hell',
  'helvete',
  'hoar',
  'hoer',
  'honkey',
  'hoor',
  'hoore',
  'hore',
  'huevon',
  'hui',
  'injun',
  'jackoff',
  'jap',
  'jerkoff',
  'jisim',
  'jism',
  'jiss',
  'jizm',
  'jizz',
  'kanker',
  'kawk',
  'kike',
  'klootzak',
  'knob',
  'knobz',
  'knulle',
  'kraut',
  'kuksuger',
  'kunt',
  'kuntz',
  'kurac',
  'kurwa',
  'kusi',
  'kyrpa',
  'l3itch',
  'lesbian',
  'lesbo',
  'lezzian',
  'lipshits',
  'lipshitz',
  'mamhoon',
  'masochist',
  'masokist',
  'massterbait',
  'masstrbait',
  'masstrbate',
  'masterbaiter',
  'masterbat',
  'masterbat3',
  'masterbate',
  'masturbat',
  'masturbate',
  'merd',
  'mibun',
  'mofo',
  'monkleigh',
  'motha',
  'mothafucker',
  'mothafuker',
  'mothafukkah',
  'mothafukker',
  'motherfucker',
  'motherfukah',
  'motherfuker',
  'motherfukkah',
  'motherfukker',
  'mouliewop',
  'muie',
  'mulkku',
  'muschi',
  'mutha',
  'muthafucker',
  'muthafukah',
  'muthafuker',
  'muthafukkah',
  'muthafukker',
  'n1gr',
  'nastt',
  'nasty',
  'nazi',
  'nepesaurio',
  'nigga',
  'niggas',
  'nigger',
  'nigur',
  'niiger',
  'niigr',
  'nutsack',
  'orafis',
  'orgasim',
  'orgasm',
  'orgasum',
  'oriface',
  'orifice',
  'orifiss',
  'orospu',
  'p0rn',
  'packi',
  'packie',
  'packy',
  'paki',
  'pakie',
  'paky',
  'paska',
  'pecker',
  'peeenus',
  'peeenusss',
  'peenus',
  'peinus',
  'pen1s',
  'penas',
  'penis',
  'penisbreath',
  'penus',
  'penuus',
  'perse',
  'phuc',
  'phuck',
  'phuk',
  'phuker',
  'phukker',
  'picka',
  'pierdol',
  'pillu',
  'pimmel',
  'pimpis',
  'piss',
  'pizda',
  'polac',
  'polack',
  'polak',
  'poonani',
  'poontsee',
  'poop',
  'porn',
  'pr0n',
  'pr1c',
  'pr1ck',
  'pr1k',
  'preteen',
  'pula',
  'pule',
  'pusse',
  'pussee',
  'pussy',
  'puta',
  'puto',
  'puuke',
  'puuker',
  'qahbeh',
  'queef',
  'queer',
  'queerz',
  'qweers',
  'qweerz',
  'qweir',
  'rautenberg',
  'recktum',
  'rectum',
  'retard',
  's.o.b.',
  'sadist',
  'scank',
  'schaffer',
  'scheiss',
  'schlampe',
  'schlong',
  'schmuck',
  'screw',
  'scrotum',
  'semen',
  'sex',
  'sexx',
  'sexxx',
  'sexy',
  'sh1ter',
  'sh1ts',
  'sh1tter',
  'sh1tz',
  'sharmuta',
  'sharmute',
  'shemale',
  'shipal',
  'shit',
  'shitt',
  'shitter',
  'shitty',
  'shity',
  'shitz',
  'shiz',
  'shyte',
  'shytty',
  'skanck',
  'skank',
  'skankee',
  'skankey',
  'skanky',
  'skrib',
  'slut',
  'slutty',
  'slutz',
  'smut',
  'sonofabitch',
  'sx',
  'teets',
  'teez',
  'testical',
  'testicle',
  'tit',
  'titt',
  'turd',
  'va1jina',
  'vag1na',
  'vagiina',
  'vagina',
  'vaj1na',
  'vajina',
  'vullva',
  'vulva',
  'w00se',
  'w0p',
  'wank',
  'wh00r',
  'wh0re',
  'whoar',
  'whore',
  'xrated',
  'xxx',
];
